### ISSUE TITLE
Can't select files other than png

### ISSUE THREAD

**Issue by ghost** [hansemannn/titanium-document-picker#1]
Hey,

I was excited to find your repo because it's exactly what I need for my project.
But for some reason I'm not able to select any file other than png (even if I remove png from the type array).
Here's my code (it's inside an Appcelerator sample project):
```javascript
function doClick(e) {
    let docPicker = require('ti.documentpicker');
    docPicker.showDocumentPicker({
        type: ['public.mp3'],
        allowsMultipleSelection: false,
        onSelect: event => {
            console.warn(event.documents);
        }
    });
}
```
I'm using Appcelerator CLI 8.1.1 and SDK 9.3.2.GA.
Am I missing something here?

**Comment by hansemannn** [comment]
Closing for now - if this is still an issue, let me know!
